#!/usr/bin/env python3
"""Write public release file checksums for Northsignal Labs.

Filesystem-only integrity handoff. It reads RELEASE-MANIFEST.json, hashes each
manifest-approved public file except CHECKSUMS.txt itself, and writes a static
CHECKSUMS.txt file a reviewer can use to spot stale or incomplete upload trees
before an approved public launch.

It does not publish, upload, authenticate, create accounts, contact services,
collect data, add analytics, create payment/KYC/quote/invoice workflows, or
spend money.
"""
from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "RELEASE-MANIFEST.json"
OUT = ROOT / "CHECKSUMS.txt"
SELF_NAME = "CHECKSUMS.txt"


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def load_required_files() -> list[str]:
    if not MANIFEST.exists():
        raise FileNotFoundError(f"missing manifest: {MANIFEST.relative_to(ROOT)}")
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    required = manifest.get("required_files")
    if not isinstance(required, list) or not required:
        raise ValueError("RELEASE-MANIFEST.json required_files must be a non-empty list")
    return [str(item) for item in required]


def main() -> int:
    errors: list[str] = []
    required_files = load_required_files()
    checksum_targets = [rel_path for rel_path in required_files if rel_path != SELF_NAME]

    rows: list[tuple[str, int, str]] = []
    for rel_path in checksum_targets:
        path = ROOT / rel_path
        if not path.exists() or not path.is_file():
            errors.append(f"missing manifest-approved file: {rel_path}")
            continue
        rows.append((rel_path, path.stat().st_size, sha256_file(path)))

    if errors:
        print("Northsignal Labs release checksum writer")
        print(f"errors: {len(errors)}")
        for error in errors:
            print(f"ERROR: {error}")
        return 1

    lines = [
        "# Northsignal Labs MSP Security Reporting Template Pack — public file checksums",
        "",
        "Generated by: tools/write_release_checksums.py",
        "Source manifest: RELEASE-MANIFEST.json",
        f"Manifest-approved files hashed: {len(rows)}",
        "Excluded from this self-check: CHECKSUMS.txt (this file)",
        "",
        "Use: after an approved no-spend public-channel URL/account exists, compare this file against the upload tree or ZIP contents before publishing/reviewing. If any hash/byte count differs, rerun local gates and do not treat the artifact as launch-ready.",
        "Guardrails: filesystem-only integrity aid; no account creation, upload, public posting, analytics, forms, contact capture, payment/KYC, quote/invoice workflow, or spend is authorized by this file.",
        "",
        "| SHA-256 | Bytes | Path |",
        "|---|---:|---|",
    ]
    for rel_path, size, digest in sorted(rows):
        lines.append(f"| `{digest}` | {size} | `{rel_path}` |")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print("Northsignal Labs release checksum writer")
    print(f"manifest-approved files hashed: {len(rows)}")
    print(f"wrote: {OUT.relative_to(ROOT)}")
    print("errors: 0")
    return 0


if __name__ == "__main__":
    sys.exit(main())
